server:
  port: 1100

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: service_authentication
    password: service_authentication
    app-id: service_authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/tpfdb?currentSchema=authentication
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
security:
  oauth2:
    client:
      client-id: service_authentication
      client-secret: service_authentication
      access-token-uri: http://localhost:1100/oauth/token
    resource:
      token-info-uri: http://localhost:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.0.200:5432/tpfdb?currentSchema=authentication
eureka:
  client:
    serviceUrl:
      defaultZone: tpf-service-config:8761/eureka