server:
  port: 1200

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: service_authorization
    password: service_authorization
    template:
      exchange: service_authorization
      default-receive-queue: service_authorization
      routing-key: service_authorization
  datasource:
    url: jdbc:postgresql://localhost:5432/tpfdb?currentSchema=authentication
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
security:
  oauth2:
    client:
      client-id: service_authorization
      client-secret: service_authorization
    resource:
      token-info-uri: http://localhost:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.0.200:5432/tpfdb?currentSchema=authentication
