server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:  
    tpf_service_authentication:
      path: /api/auth/**
      sensitiveHeaders:
      serviceId: TPF-SERVICE-AUTHENTICATION
    tpf_service_restclient:
      path: /api/**
      sensitiveHeaders: 
      serviceId: TPF-SERVICE-RESTCLIENT
  add-proxy-headers: true
  
ribbon:
  ReadTimeout: 150000
  ConnectTimeout: 60000  
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 40000

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://tpf-service-eureka:8761/eureka
