server:
  port: 4000
spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  rabbitmq:
    host: localhost
    port: 5672
    username: tpf-service-restclient
    password: tpf-service-restclient
    app-id: tpf-service-restclient
security:
  oauth2:
    client:
      client-id: tpf-service-restclient
      client-secret: tpf-service-restclient
    resource:
      token-info-uri: http://localhost:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
---
spring:
  profiles: dev
  cloud:
    config:
      allow-override: false
      override-none: false
  rabbitmq:
    host: tpf-opensource-rabbitmq
security:
  oauth2:
    resource:
      token-info-uri: http://tpf-service-authentication:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone:  http://tpf-service-eureka:8761/eureka
  instance:
    hostname: tpf-service-restclient
