server:
  port: 1100
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: tpf-service-authentication
    password: tpf-service-authentication
    app-id: tpf-service-authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/tpfdb?currentSchema=authentication
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
security:
  oauth2:
    client:
      client-id: tpf-service-authentication
      client-secret: tpf-service-authentication
    resource:
      token-info-uri: http://localhost:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
---
spring:
  profiles: dev
  rabbitmq:
    host: tpf-opensource-rabbitmq
  datasource:
    url: jdbc:postgresql://192.168.0.200:5432/tpfdb?currentSchema=authentication
security:
  oauth2:
    resource:
      token-info-uri: http://tpf-service-authentication:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone: http://tpf-service-eureka:8761/eureka