server:
  port: 8761
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: tpf-service-eureka
    password: tpf-service-eureka
    app-id: tpf-service-eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    preferSameZoneEureka: true
  instance:
    preferIpAddress: true
  server:
      waitTimeInMsWhenSyncEmpty: 5
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
---
spring:
  profiles: dev
  rabbitmq:
    host: tpf-opensource-rabbitmq
