server:
  port: 4000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: tpf-service-restclient
    password: tpf-service-restclient
    app-id: tpf-service-restclient
security:
  oauth2:
    client:
      client-id: tpf-service-restclient
      client-secret: tpf-service-restclient
    resource:
      token-info-uri: http://localhost:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

---
spring:
  profiles: dev
  rabbitmq:
    host: tpf-opensource-rabbitmq
security:
  oauth2:
    resource:
      token-info-uri: http://tpf-service-authentication:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone:  http://tpf-service-eureka:8761/eureka
