server:
  port: 4000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: tpf_service_restclient
    password: tpf_service_restclient
    app-id: tpf_service_restclient
security:
  oauth2:
    client:
      client-id: tpf_service_restclient
      client-secret: tpf_service_restclient
    resource:
      token-info-uri: http://localhost:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
